### ISSUE TITLE
Suggest changing NEXTAUTH_URL implementation

### ISSUE THREAD

**Issue by dcoder4** [aws-samples/deploy-langfuse-on-ecs-with-fargate#2]
When trying to convert this application to be production ready NEXTAUTH_URL is hardcoded to be the load_balancer_url (line  #73) in the ecs_task.py.

For production assuming you want to put on SSL, a custom domain, and use SSO (like Cognito) this setting is hard to override (and would be incorrect).

Suggest the line is modified to first check if an environment variable within 'langfuse_env' called 'NEXTAUTH_URL' exists first, before hardcoding it to the load_balancer_url. This would then be more inline with the LangFuse documentation.

This would save a couple of hours of head scratching and needless debugging of why SSO keeps reverting back to the loadbalancer url.

Cheers!

**Comment by ksmin23** [comment]
Thanks for your suggestion.
In this project, I assumed that Langfuse server uses http protocol instead of https.
So, if you want to use SSO (like Cognito), then you are able to do it by the following instructions:
(Step 1) modify ApplicationLoadBalancerStack in the `alb.py` to support https protocol and `load_balancer_url` url scheme.
(Step 2) add the environment variables related with SSO (e.g., `AUTH_COGNITO_CLIENT_ID`, `AUTH_COGNITO_CLIENT_SECRET`, `AUTH_COGNITO_ISSUER` for Cognito) into `langfuse_env` in the `cdk.context.json`

After completion of the above steps, you can deploy Langfuse on Amazon ECS and use SSL.
